services:
  mysqldb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - $HOME/database:/var/lib/mysql
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql:ro # 自动执行sql文件
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "jinxin"
      MYSQL_DATABASE: "patientsdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "jinxin"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb # SERVICE_NAME
      DB_PORT: 3306
      DB_USER: "admin"
      DB_PASSWORD: "jinxin"
      DB_NAME: patientsdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on: # mysql service must run fist
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
